# Standard base from kitchen-docker
FROM <%= @image %>
<% case @platform
   when 'debian', 'ubuntu' %>
<% if @disable_upstart %>
RUN dpkg-divert --local --rename --add /sbin/initctl
RUN ln -sf /bin/true /sbin/initctl
<% end %>
ENV DEBIAN_FRONTEND noninteractive
RUN apt-get update
RUN apt-get install -y sudo openssh-server curl lsb-release
<% when 'rhel', 'centos', 'fedora' %>
RUN yum clean all
RUN yum install -y sudo openssh-server openssh-clients which curl
RUN ssh-keygen -t rsa -f /etc/ssh/ssh_host_rsa_key -N ''
RUN ssh-keygen -t dsa -f /etc/ssh/ssh_host_dsa_key -N ''
<% when 'arch' %>
RUN pacman -Syu --noconfirm
RUN pacman -S --noconfirm openssh sudo curl
RUN ssh-keygen -A -t rsa -f /etc/ssh/ssh_host_rsa_key
RUN ssh-keygen -A -t dsa -f /etc/ssh/ssh_host_dsa_key
<% when 'gentoo' %>
RUN emerge sync
RUN emerge net-misc/openssh app-admin/sudo
RUN ssh-keygen -A -t rsa -f /etc/ssh/ssh_host_rsa_key
RUN ssh-keygen -A -t dsa -f /etc/ssh/ssh_host_dsa_key
<% end %>
RUN useradd -d /home/<%= @username %> -m -s /bin/bash <%= @username %>
RUN echo <%= @username %>:<%= @password %> | chpasswd
RUN echo '<%= @username %> ALL=(ALL) NOPASSWD:ALL' >> /etc/sudoers
RUN echo '<%= @username %> ALL=(ALL) NOPASSWD:ALL' >> /etc/sudoers.d/<%= @username %>
<% case @platform
   when 'rhel', 'centos', 'fedora' %>
# Restore systemd
ENV container docker
RUN yum -y remove fakesystemd && yum -y install systemd
#VOLUME /sys/fs/cgroup
<% end %>
# Run some installs at provision so they are cached in the image.
# Install Chef (with the correct verison).
RUN curl -L https://chef.io/chef/install.sh | bash -s --<%= ( !@require_chef_omnibus || @require_chef_omnibus.empty? || @require_chef_omnibus == 'latest' ) ? '' : " -v #{@require_chef_omnibus}" %>
# Install some kitchen-related gems. Normally installed during the verify step but thats idempotent.
RUN env GEM_HOME=/tmp/busser/gems GEM_PATH=/tmp/busser/gems GEM_CACHE=/tmp/busser/gems/cache /opt/chef/embedded/bin/gem install thor busser busser-serverspec serverspec
